= inspectoor-maven-plugin

A maven plugin to collect openapi files and send it to a backend application

== Features

* Print basic meta data
* Collect openapi specs
* Upload project meta data
* Generate SBOM file
* Upload the SBOM file
* Check openapi spec (not implemented yet)

== Parameters
[cols="1,1,1,3"]
|===
|Name | Required | default value |Explanation

|checkspecs||none|Checks and validates every found openapi file.

none -> ignore

warn -> logging the warnings

fail -> stop processing
|command||1|Defines the feature:

1 -> printInfos.

2 -> printInfos and upload meta data

3 -> printInfos, upload meta data and upload the SBOM file
|ou|x||The orginaztion unit. It can contain a semicolon-separated names.
|system|x||The associated system
|tag|||Label. It can contain a semicolon-separated names.
|url|||The url of the central backend. Only required if command = 2 or 3
|apikey|||The apikey of the central backend. Only required if command = 2 or 3

|===

== Usages

----
mvn io.github.increasecurity:inspectoor-maven-plugin:inspectoor -Dou="sales;okSquad" -Dsystem="loremSystem" -Dtag="maven-plugin" -Dcommand=1
mvn io.github.increasecurity:inspectoor-maven-plugin:inspectoor -Dou="sales;okSquad" -Dsystem="loremSystem" -Dtag="maven-plugin" -Dcommand=2 --Durl="http://localhost:8081" -Dapikey="secret"
----
